[tool.poetry]
name = "data-schema"
version = "0.1.0"
description = ""
authors = ["AlexWu <alexwu@going.cloud>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pydantic = "^2.10.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
