services:
  debug:
    image: node:20-alpine
    volumes:
      - .:/app
    ports:
      - 8000:8000
      - 9229:9229
    entrypoint: ""
    working_dir: /app
    command:
      - npm
      - run
      - debug
    stop_grace_period: 1s
  sls_debug:
    image: node:20-alpine
    volumes:
      - .:/app
      - ~/.serverlessrc:/root/.serverlessrc # pass serverless credential into container
    ports:
      - 3000:3000
      - 19229:19229
    entrypoint: ""
    working_dir: /app
    command:
      - npm
      - run
      - sls:debug
    stop_grace_period: 1s
