# Ref: https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml

service: js-debug

provider:
  name: aws
  runtime: nodejs20.x
  region: "ap-northeast-1"
  stage: local
  architecture: arm64
  environment:
    NODE_OPTIONS: --enable-source-maps

  memorySize: 128
  timeout: 30

useDotenv: true

plugins:
  - serverless-offline

# https://www.serverless.com/framework/docs/providers/aws/guide/building#plugin-conflicts
build:
  esbuild: false

functions:
  ts-api:
    handler: dist/handler.handler
    events:
      - httpApi: "ANY /ts/{proxy+}"
  js-api:
    handler: handler.handler
    events:
      - httpApi: "ANY /js/{proxy+}"
