DROP TABLE IF EXISTS t_identity;
DROP TABLE IF EXISTS t_uuidv4;
DROP TABLE IF EXISTS t_uuidv7;
CREATE TABLE t_identity (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  payload TEXT
) ENGINE = InnoDB;
-- BINARY(16) 做 PK；插入時用 UUID_TO_BIN(?, 1) 優化順序性
CREATE TABLE t_uuidv4 (id BINARY(16) PRIMARY KEY, payload TEXT) ENGINE = InnoDB;
CREATE TABLE t_uuidv7 (id BINARY(16) PRIMARY KEY, payload TEXT) ENGINE = InnoDB;
