version: "3.8"

services:
  http:
    build:
      context: ./app/http
      dockerfile: Dockerfile
    # curl -XPOST "http://localhost:9001/2015-03-31/functions/function/invocations" -d '{}'
    ports:
      - 9001:8080

  ws:
    build:
      context: ./app/ws
      dockerfile: Dockerfile
    # curl -XPOST "http://localhost:9002/2015-03-31/functions/function/invocations" -d '{}'
    ports:
      - 9002:8080
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_REGION}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_REGION=${AWS_REGION}
      - LAMBDA_ENDPOINT=http://lite-hub:3001
      - API_GATEWAY_ENDPOINT=http://lite-hub:3002/dev # stage is required

  worker:
    build:
      context: ./app/worker
      dockerfile: Dockerfile
    # curl -XPOST "http://localhost:9003/2015-03-31/functions/function/invocations" -d '{}'
    ports:
      - 9003:8080

  lite-hub:
    restart: always
    build:
      context: ./lite-hub
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      - 3001:3001
      - 3002:3002
    environment:
      - FUNCTION_ENDPOINT=ws=http://ws:8080,http=http://http:8080,worker=http://worker:8080
      - PATH_MAPPING=/http=http
      - WS_FUNCTION=ws
    stop_grace_period: 1s
