version: "3.7"

volumes:
  prometheus_data: {}
  grafana_data: {}

networks:
  prom:

services:
  prometheus:
    image: prom/prometheus:v2.36.2
    volumes:
      - ./conf/prom/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    ports:
      - 9090:9090
    depends_on:
      - pushgateway
    networks:
      - prom
    restart: always

  pushgateway:
    image: prom/pushgateway
    restart: always
    expose:
      - 9091
    ports:
      - "9091:9091"
    networks:
      - prom

  grafana:
    image: grafana/grafana
    user: "472"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./conf/grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./conf/grafana/.env
    networks:
      - prom
    restart: always
