version: '3'

services:
  rabbitmq:
    image: heidiks/rabbitmq-delayed-message-exchange
    ports:
      - 5672:5672
      - 15672:15672
    # environment:
    #   - RABBITMQ_DEFAULT_USER=admin
    #   - RABBITMQ_DEFAULT_PASS=password

  redis:
    image: redis
    ports:
      - 6379:6379
